### ISSUE TITLE
Party > Auras > Debuffs > Show only dispellable not working

### ISSUE THREAD

**Issue by abstract-entity** [vendethiel/GladiusEx#62]
Party > Auras > Debuffs > Show only dispellable not working, is not working, it filter all debuffs

When i don't check option, dispellable debuffs appears
![image](https://user-images.githubusercontent.com/1453538/211805250-3697191b-16e8-4002-be11-93ad09c98b3f.png)

When i check option, dispellable debuffs disapears
![image](https://user-images.githubusercontent.com/1453538/211805481-323e36db-ae7f-4a79-b620-0b71e3af11b6.png)

**Comment by vendethiel** [comment]
I should have a fix in the next version.

**Comment by pmbednarczyk** [comment]
When can we expect next version @vendethiel ? :)

**Comment by vendethiel** [comment]
I released 2.6.1, which should fix it.

**Comment by pmbednarczyk** [comment]
THX, but for me this problem still occurs :(
![image](https://user-images.githubusercontent.com/16899307/214665111-d6307418-ee89-46a5-b60a-971d98fe1b9a.png)
![image](https://user-images.githubusercontent.com/16899307/214665153-fb09f6ea-e418-4a49-a43b-1789dff3e65c.png)

**Comment by vendethiel** [comment]
Just pushed 2.6.2, will be available on CF/wago approves the new file.
